#if UNITY_EDITOR
using UnityEngine;
using UnityEditor;
using Features.Enemy.Data;
using System;

namespace Features.Enemy.Editor
{
    [CustomEditor(typeof(EnemyDatabaseSO))]
    public class EnemyDatabaseEditor : UnityEditor.Editor
    {
        private EnemyDatabaseSO db;

        private void OnEnable()
        {
            db = (EnemyDatabaseSO)target;
        }

        public override void OnInspectorGUI()
        {
            serializedObject.Update();

            EditorGUILayout.LabelField("ENEMY DATABASE", EditorStyles.boldLabel);
            EditorGUILayout.Space(5);

            DrawAddEnemyButton();
            EditorGUILayout.Space(10);

            if (db.enemies == null || db.enemies.Length == 0)
            {
                EditorGUILayout.HelpBox("Database is empty. Add enemies using the button above.", MessageType.Info);
            }
            else
            {
                DrawEnemyList();
            }

            serializedObject.ApplyModifiedProperties();
        }

        // ===========================================================
        // UI: Button "Add enemy"
        // ===========================================================
        private void DrawAddEnemyButton()
        {
            if (GUILayout.Button("➕ Add Enemy"))
            {
                Undo.RecordObject(db, "Add Enemy");

                Array.Resize(ref db.enemies, (db.enemies?.Length ?? 0) + 1);

                var newConfig = CreateEnemyConfigSO();
                db.enemies[db.enemies.Length - 1] = newConfig;

                EditorUtility.SetDirty(db);
                AssetDatabase.SaveAssets();
            }
        }

        // ===========================================================
        // UI: List of enemies
        // ===========================================================
        private void DrawEnemyList()
        {
            for (int i = 0; i < db.enemies.Length; i++)
            {
                var cfg = db.enemies[i];

                if (cfg == null)
                {
                    EditorGUILayout.HelpBox($"Null entry #{i}. Remove or replace.", MessageType.Warning);
                    continue;
                }

                EditorGUILayout.BeginVertical("box");

                EditorGUILayout.BeginHorizontal();
                EditorGUILayout.LabelField($"{i + 1}. {cfg.enemyId}", EditorStyles.boldLabel);

                if (GUILayout.Button("Open", GUILayout.Width(50)))
                    Selection.activeObject = cfg;

                if (GUILayout.Button("X", GUILayout.Width(25)))
                {
                    RemoveEnemy(i);
                    return;
                }
                EditorGUILayout.EndHorizontal();

                // Draw config reference
                db.enemies[i] = (EnemyConfigSO)EditorGUILayout.ObjectField("Config", cfg, typeof(EnemyConfigSO), false);

                // Draw ID field
                string newId = EditorGUILayout.TextField("Enemy ID", cfg.enemyId);

                if (newId != cfg.enemyId)
                {
                    Undo.RecordObject(cfg, "Change EnemyId");
                    cfg.enemyId = newId;
                    EditorUtility.SetDirty(cfg);
                }

                // Duplicate check
                if (HasDuplicateId(cfg, i))
                {
                    EditorGUILayout.HelpBox($"Duplicate ID: {cfg.enemyId}", MessageType.Error);
                }

                EditorGUILayout.EndVertical();
            }
        }

        private bool HasDuplicateId(EnemyConfigSO cfg, int index)
        {
            if (string.IsNullOrWhiteSpace(cfg.enemyId))
                return false;

            for (int j = 0; j < db.enemies.Length; j++)
            {
                if (j == index) continue;
                if (db.enemies[j] != null && db.enemies[j].enemyId == cfg.enemyId)
                    return true;
            }
            return false;
        }

        // ===========================================================
        // Remove enemy entry
        // ===========================================================
        private void RemoveEnemy(int index)
        {
            Undo.RecordObject(db, "Remove Enemy");

            for (int i = index; i < db.enemies.Length - 1; i++)
                db.enemies[i] = db.enemies[i + 1];

            Array.Resize(ref db.enemies, db.enemies.Length - 1);

            EditorUtility.SetDirty(db);
            AssetDatabase.SaveAssets();
        }

        // ===========================================================
        // Create new EnemyConfigSO with autogenerated ID
        // ===========================================================
        private EnemyConfigSO CreateEnemyConfigSO()
        {
            string guid = Guid.NewGuid().ToString("N").Substring(0, 6);
            string id = $"enemy_{guid}";

            var cfg = ScriptableObject.CreateInstance<EnemyConfigSO>();
            cfg.enemyId = id;
            cfg.displayName = $"Enemy {guid}";

            // Save SO next to database
            string dbPath = AssetDatabase.GetAssetPath(db);
            string folder = System.IO.Path.GetDirectoryName(dbPath);
            string assetPath = $"{folder}/Enemy_{guid}.asset";

            AssetDatabase.CreateAsset(cfg, assetPath);
            AssetDatabase.SaveAssets();

            return cfg;
        }
    }
}
#endif
